[package]

name = "renderer"
version = "0.0.1"
authors = ["Nathan Levesque <rhysyngsun@gmail.com>"]

[[bin]]
name = "renderer"
test = false
doc = false
bench = false

[dev_dependencies]
quickcheck_macros = "*"
